# C++
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
#[[plugins]]
#repo = 'tweekmonster/deoplete-clang2'
#if = 'has("nvim")'
#on_ft = ['c', 'cpp']
#hook_source = '''
#  autocmd FileType c,cpp let b:clang2_orig_maps = {}
#'''

# Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
[[plugins]]
repo = 'zchee/deoplete-jedi'
if = 'has("nvim")'
on_ft = 'python3'
hook_add = '''
  let g:deoplete#sources#jedi#python_path = $HOME . '/.pyenv/shims/python3'
'''

# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 1
  let g:go_doc_keywordprg_enabled = 1
  let g:go_metalinter_autosave = 0
'''
[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

# CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# Markdown
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
#[[plugins]]
#repo = 'plasticboy/vim-markdown'
#on_ft = 'markdown'

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex']

# HCL
[[plugins]]
repo = 'hashicorp/terraform'
on_ft = ['tf']

# Dockerfile
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

# Jinja2
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
hook_source = '''
  au BufNewFile,BufRead *.jinja2,*.jinja setf jinja
'''
on_ft = ['jinja']
