# Color
  [[plugins]]
  repo = 'joshdick/onedark.vim'
  [[plugins]]
  repo = 'w0ng/vim-hybrid'
  [[plugins]]
  repo = 'nanotech/jellybeans.vim'
  [[plugins]]
  repo = 'vim-scripts/tir_black'
  [[plugins]]
  repo = 'tomasr/molokai'
  [[plugins]]
  repo = 'vim-scripts/Wombat'

# snippet
  [[plugins]]
  repo = 'Shougo/neosnippet'

# コンテキストによって filetype 自動切り替え
  [[plugins]]
  repo = 'Shougo/context_filetype.vim'

# template 呼び出し
  [[plugins]]
  repo = 'mattn/sonictemplate-vim'
  hook_add = '''
    let g:sonictemplate_vim_template_dir = [
        \ '~/.cache/sonictemplate'
        \]
  '''

# 窓移動系
  [[plugins]]
  repo = 'kana/vim-operator-user'
  [[plugins]]
  repo = 'kana/vim-submode'

# ファイル探索
  [[plugins]]
  repo = 'scrooloose/nerdtree'
  hook_add = '''
    nnoremap tr :<C-u>NERDTreeToggle<CR>
    let g:NERDTreeShowHidden=1
    let g:NERDTreeMapUpdir=''
    let g:NERDTreeShowBookmarks=1
    let g:NERDTreeMapOpenSplit='<C-j>'
    let g:NERDTreeMapOpenVSplit='<C-l>'
  '''

# Syntax Check
  [[plugins]]
  repo = 'w0rp/ale'
  hook_add = '''
    let g:ale_lint_on_text_changed = 'never'
    let g:ale_set_loclist = 0
    let g:ale_set_quickfix = 1
    let g:ale_sign_column_always = 1
    let g:ale_lint_on_enter = 0
    let g:ale_open_list = 1
    let g:ale_keep_list_window_open = 0
  '''

# vim-surround
  [[plugins]]
  repo = 'tpope/vim-surround'

# インデント表示
  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'

# 画面下部 line 表示
  [[plugins]]
  repo = 'itchyny/lightline.vim'

# 文末空白の可視化
  [[plugins]]
  repo = 'bronson/vim-trailing-whitespace'
  hook_add = '''
    noremap tw :FixWhitespace<CR>:%s/\t/    /g<CR>
  '''

# Git
  [[plugins]]
  repo = 'tpope/vim-fugitive'
  hook_add = '''
    nnoremap :gs :Gstatus
    nnoremap :ga :Gwrite
    nnoremap :gr :Gread
    nnoremap :gc :Gcommit
    nnoremap :gb :Gblame
    nnoremap :gd :Gdiff
  '''
  [[plugins]]
  repo = 'hotwatermorning/auto-git-diff'
  hook_add = '''
    let g:auto_git_diff_disable_auto_update = 1
    nmap <Leader>gd <Plug>(auto_git_diff_manual_update)
  '''

# ssh 先も p でクリップボード共有
  [[plugins]]
  repo = 'haya14busa/vim-poweryank'
  hook_add = '''
    map <Leader>y <Plug>(operator-poweryank-osc52)
  '''

# 日本語の w, b, e 移動補助
  [[plugins]]
  repo = 'deton/jasegment.vim'

# オートセーブ
  [[plugins]]
  repo = 'vim-scripts/vim-auto-save'
  hook_add = '''
    let g:auto_save = 1
  '''

# vim からブラウザを開く
  [[plugins]]
  repo = 'tyru/open-browser.vim'
  hook_add = '''
    " Open URL
    nnoremap <Leader>o <Plug>(openbrowser-open)
    vnoremap <Leader>o <Plug>(openbrowser-open)
    " Search on Google
    nnoremap <Leader>g :<C-u>OpenBrowserSearch<Space><C-r><C-w><Enter>
  '''

# QuickRun
  [[plugins]]
  repo = 'thinca/vim-quickrun'
  [[plugins]]
  repo = 'osyo-manga/shabadou.vim'

# vimproc
  [[plugins]]
  repo = 'Shougo/vimproc'

# メモ書き
  [[plugins]]
  repo = 'glidenote/memolist.vim'
  hook_add = '''
    let g:memolist_memo_suffix = "md"
    if isdirectory($HOME . "/GoogleDrive")
      let g:memolist_path = $HOME . "/GoogleDrive/Memo"
    endif
  '''

# neovim
  [[plugins]]
  repo = 'Shougo/deoplete.nvim'
  if = 'has("nvim")'
  hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    let g:deoplete#enable_camel_case = 0
    let g:deoplete#enable_ignore_case = 0
    let g:deoplete#enable_refresh_always = 0
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#file#enable_buffer_path = 1
    let g:deoplete#max_list = 10000
  '''
  [[plugins]]
  repo = 'Shougo/denite.nvim'
  if = 'has("nvim")'
  [[plugins]]
  repo = 'Shougo/neoyank.vim'
  depends = ['Shougo/denite.nvim']

