# C++ (TODO: lsp に移行)
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
#[[plugins]]
#repo = 'tweekmonster/deoplete-clang2'
#if = 'has("nvim")'
#on_ft = ['c', 'cpp']
#hook_source = '''
#  autocmd FileType c,cpp let b:clang2_orig_maps = {}
#'''

# Python (TODO: lsp に移行)
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

# Go
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

# HTML
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

# CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_source = '''
  au BufRead,BufNewFile *.md set filetype=markdown
'''
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:previm_open_cmd = ''
  let g:previm_disable_default_css = 1
  let g:previm_custom_css_path = '~/.config/previm/markdown.css'
  nnoremap sm :PrevimOpen<CR>
'''

## LaTeX
#[[plugins]]
#repo = 'lervag/vimtex'
#on_ft = ['tex', 'latex']

# HCL
[[plugins]]
repo = 'hashicorp/terraform'
on_ft = ['tf']

# Dockerfile
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

# Jinja2
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = ['jinja']
hook_source = '''
  autocmd BufNewFile,BufRead *.jinja2,*.jinja setf jinja
'''

# Jsonnet
[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = ['jsonnet']
hook_source = '''
  autocmd BufNewFile,BufRead *.jsonnet setf jsonnet
'''

# Rego
[[plugins]]
repo = 'tsandall/vim-rego'
hook_source = '''
  au BufNewFile,BufRead *.rego setf rego
'''
on_ft = ['rego']
