# C++
  [[plugins]]
  repo = 'thinca/vim-quickrun'
  on_ft = ['c', 'cpp']

  [[plugins]]
  repo = 'rhysd/vim-clang-format'
  on_ft = ['c', 'cpp']

  [[plugins]]
  repo = 'Shougo/neoinclude.vim'
  on_ft = ['c', 'cpp']

#  [[plugins]]
#  repo = 'zchee/deoplete-clang'
#  on_ft = ['c', 'cpp']

# Python
  [[plugins]]
  repo = 'davidhalter/jedi-vim'
  on_ft = 'python'

  [[plugins]]
  repo = 'kevinw/pyflakes-vim'

  [[plugins]]
  repo = 'nvie/vim-flake8'

# Go
#  [[plugins]]
#  repo = 'vim-jp/vim-go-extra'
#  on_ft = 'go'

  [[plugins]]
  repo = 'fatih/vim-go'
  on_ft = 'go'

  [[plugins]]
  repo = 'zchee/deoplete-go'
  on_ft = 'go'

# HTML
  [[plugins]]
  repo = 'mattn/emmet-vim'
  on_ft = 'html'

# CSS
  [[plugins]]
  repo = 'hail2u/vim-css3-syntax'
  on_ft = 'css'

# JavaScript
  [[plugins]]
  repo = 'pangloss/vim-javascript'
  on_ft = 'javascript'

# Markdown
#  [[plugins]]
#  repo = 'plasticboy/vim-markdown'
#  on_ft = 'markdown'

  [[plugins]]
  repo = 'kannokanno/previm'
  on_ft = 'markdown'
