## snippet
#  [[plugins]]
#  repo = 'Shougo/neosnippet'
## snippet
#  [[plugins]]
#  repo = 'Shougo/neosnippet-snippets'
# コンテキストによって filetype 自動切り替え
  [[plugins]]
  repo = 'Shougo/context_filetype.vim'
  [[plugins]]
  repo = 'Shougo/neoyank.vim'
# template 呼び出し
  [[plugins]]
  repo = 'mattn/sonictemplate-vim'
#  [[plugins]]
#  repo = 'ervandew/supertab'
# 窓移動系
  [[plugins]]
  repo = 'kana/vim-operator-user'
  [[plugins]]
  repo = 'kana/vim-submode'
# ファイル探索系
  [[plugins]]
  repo = 'scrooloose/nerdtree'
  [[plugins]]
  repo = 'scrooloose/syntastic'
# vim-surround
  [[plugins]]
  repo = 'tpope/vim-surround'
# インデント表示
  [[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'
# 画面下部 line 表示
  [[plugins]]
  repo = 'itchyny/lightline.vim'
# 文末空白の可視化
  [[plugins]]
  repo = 'bronson/vim-trailing-whitespace'
# Git
  [[plugins]]
  repo = 'tpope/vim-fugitive'
  [[plugins]]
  repo = 'hotwatermorning/auto-git-diff'
# 貼り付け時ペーストモードに
  [[plugins]]
  repo = 'ConradIrwin/vim-bracketed-paste'
# ssh 先も p でクリップボード共有
  [[plugins]]
  repo = 'haya14busa/vim-poweryank'
# 日本語の w, b, e 移動補助
  [[plugins]]
  repo = 'deton/jasegment.vim'
# オートセーブ
  [[plugins]]
  repo = 'vim-scripts/vim-auto-save'
# vim からブラウザを開く
  [[plugins]]
  repo = 'tyru/open-browser.vim'
# QuickRun
  [[plugins]]
  repo = 'thinca/vim-quickrun'
  [[plugins]]
  repo = 'osyo-manga/shabadou.vim'
# vimproc
  [[plugins]]
  repo = 'Shougo/vimproc'
# ANSI color を表示
  [[plugins]]
  repo = 'vim-scripts/AnsiEsc.vim'
# Color
  [[plugins]]
  repo = 'joshdick/onedark.vim'
  [[plugins]]
  repo = 'w0ng/vim-hybrid'
  [[plugins]]
  repo = 'nanotech/jellybeans.vim'
  [[plugins]]
  repo = 'vim-scripts/tir_black'
  [[plugins]]
  repo = 'tomasr/molokai'
  [[plugins]]
  repo = 'vim-scripts/Wombat'
# メモ書き
  [[plugins]]
  repo = 'glidenote/memolist.vim'

# neovim
  [[plugins]]
  repo = 'Shougo/deoplete.nvim'
  if = 'has("nvim")'
  depends = 'context_filetype.vim'
  on_i = 1
  [[plugins]]
  repo = 'Shougo/denite.nvim'
  if = 'has("nvim")'
# Vue
  [[plugins]]
  repo = 'posva/vim-vue'
# LSP
  [[plugins]]
  repo = 'prabirshrestha/async.vim'
  [[plugins]]
  repo = 'prabirshrestha/vim-lsp'
  [[plugins]]
  repo = 'prabirshrestha/asyncomplete.vim'
  [[plugins]]
  repo = 'prabirshrestha/asyncomplete-lsp.vim'
  [[plugins]]
  repo = 'natebosch/vim-lsc'
