#!/usr/bin/env sh
# Auther: Kitazawa
# Dotfile overwrite.

# function: deploy the simbolic link
dtsl(){
	if [ -L ~/$1 ]; then
		echo "$1 has already deployed to ~/"
		return 0
	elif [ -f ~/$1 ]; then
		rm ~/$1
	fi
	ln -s ~/dotfiles/$1 ~/
	echo "$1 is deploy to ~/"
}


if [ "$(uname)" == 'Darwin' ]; then dtsl .inputrc; fi
dtsl .gitconfig
dtsl .gitignore
dtsl .tmux.conf

# .bashrc_self
if [ -L ~/.bashrc_self ]; then
	unlink ~/.bashrc_self
elif [ -f ~/.bashrc_self ]; then
	rm ~/.bashrc_self
else
	echo "if [ -f ~/.bashrc_self ]; then source ~/.bashrc_self; fi" >> ~/.bashrc
fi
	ln -s ~/dotfiles/.bashrc_self ~/
	echo ".bashrc_self is deploy to ~/"

# vim plugin
if [ ! -d ~/.vim ];then
	mkdir ~/.vim
	for i in $(ls ~/dotfiles/.vim/ | grep -v bundle)
	do
		ln -s ~/dotfiles/.vim/$i ~/.vim/
	done
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > ~/.vim/install.sh
	sh ~/.vim/install.sh
	rm -rf ~/.vim/install.sh
	echo "Complete vim plugins Setup."
fi

# vim-undofile folder
if [ ! -d ~/vimundo ]; then
	mkdir ~/vimundo
	echo "mkdir ~/vimundo"
fi

