#!/usr/bin/env bash
# Auther: Kitazawa

# !! DOTFILE OVERWRITE !!

path=$(cd $(dirname $0) && pwd)

switch_env(){
  if [[ "$(uname)" = 'Darwin' ]]; then
    echo $2
  elif [[ "$(uname -r)" =~ ^.*-Microsoft$ ]]; then
    echo $3
  elif [[ "$(uname)" = 'Linux' ]]; then
    echo $1
  elif [[ "$(uname)" = 'FreeBSD' ]]; then
    echo $4
  fi
}

remove_file_or_check_link(){
  if [ -L $1 ]; then
    echo "$1 has already deployed"
    return 1
  elif [ -e $1 ]; then
    rm $1 -rf
  fi
  return 0
}

link_to_home(){
  ln -s $path/$1 ~/$1
  echo "$1 was deployed to ~/"
}

deploylink(){
  if remove_file_or_check_link ~/$1;then
    link_to_home $1
  fi
}


if [ "$(uname)" = 'Darwin' ]; then deploylink .inputrc; fi
deploylink .gitconfig
deploylink .gitignore
deploylink .tmux.conf
deploylink .vim
deploylink .bashrc_self
deploylink .gdbinit
deploylink .config
deploylink .vrapperrc
deploylink .latexmkrc

# let .bashrc read .bashrc_self
grep .bashrc_self ~/.bashrc > /dev/null 2>&1
if [ $? != 0 ]; then
  echo "if [ -f ~/.bashrc_self ]; then source ~/.bashrc_self; fi" >> ~/.bashrc
fi

# vim-undofile folder
if [ ! -d ~/.vimundo ]; then
  mkdir ~/.vimundo
  echo "mkdir ~/.vimundo"
fi

# link memo.conf for environment
cd ~/.config/memo
if remove_file_or_check_link $(pwd)/config.toml; then
  ln -s $(switch_env config-linux.toml config-mac.toml config-linux.toml) config.toml
fi

# download peda (gdb extention)
if [ ! -d ~/.peda ]; then
  git clone https://github.com/longld/peda ~/.peda > /dev/null 2>&1
  echo "downloaded peda"
fi

# install Powerline fonts for lightline.vim
cd ~
if [ ! -d ~/.fonts ]; then
  git clone https://github.com/powerline/fonts.git ~/.fonts > /dev/null 2>&1
  if [ $? = 0 ]; then
    cd .fonts
    if ./install.sh > /dev/null; then
      echo "install Powerline fonts"
    else
      echo "error: failed to download Powerline fonts"
    fi
  else
    echo "error: failed to download Powerline fonts"
  fi
fi
