python:
  version: 3.7.3
  packages: [neovim, jedi]
#    - neovim
#    - jedi
#    - flake8
#    - autopep8

go:
  version: 1.12.3
  packages:
    - github.com/golang/dep/cmd/dep
    - golang.org/x/tools/cmd/gopls
