#!/bin/sh

mkdir ~/.vim
if [ "$?" != "0" ]
then
	exit 1
else
	cd ~/.vim
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > install.sh
	sh ./install.sh
	rm -rf install.sh
	cd -
fi
exit 0
