#!/bin/bash

export OS='Mac'
alias l='ls'
alias ll='ls -lG'
alias lll='ls -alG'
alias updatedb='sudo /usr/libexec/locate.updatedb'
# Slideshare can't display Japanese font. (created from Keynote)
alias pdfconv="LANG=C LC_ALL=C sed -i '' s'|/Registry (Adobe) /Ordering (Japan1) /Supplement [0-9]|/Registry(Adobe) /Ordering(Identity) /Supplement 0|g'"
alias vlc="/Applications/VLC.app/Contents/MacOS/VLC"
alias wma2mp3='if [ ! -d mp3 ];then mkdir mp3; fi; for i in *; do vlc -I dummy --sout "#transcode{acodec=mp3,ab=128,channels=2,samplerate=44100}:std{access=file,mux=raw,dst=\"mp3/${i}.mp3\"}" "${i}" vlc://quit; done'
export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
