#!/bin/bash

alias l='ls'
alias ll='ls -l --color'
alias lll='ls -al --color'
alias swapsearch='grep VmSwap /proc/*/status | sort -k 2 -r | head'
alias open="cmd.exe /c start"

SSH_AGENT_FILE=$HOME/.ssh-agent
test -f $SSH_AGENT_FILE && source $SSH_AGENT_FILE > /dev/null
if [ $(ssh-add -l > /dev/null 2>&1; echo $?) = 2 ]; then
  ssh-agent > $SSH_AGENT_FILE
  source $SSH_AGENT_FILE > /dev/null
fi
