#!/bin/bash

# my function
function parse_yaml () {
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s=\"%s\"\n", vn, $2, $3);
      }
   }'
   return 0
}

# env
export EDITOR=vim
export GOPATH=$HOME/go
export PATH=$HOME/bin:$GOPATH/bin:$PATH

# alias
alias rm="rm -i"
alias cp="cp -i"
alias g="git"
alias ssh-keyadd="ssh-add ~/.ssh/id_rsa*"
alias ssh-showpub="ssh-keygen -yf"
alias vimtmp='vim `date +%Y%m%d-%H%M%S`.txt'
if [[ -x $(which colordiff) ]]; then alias diff='colordiff'; fi
if [[ -x $(which nvim) ]]; then
  alias vim='nvim'
  function vimide (){
    nvim -u ~/.vim/ide.vim $@
  }
fi
if [[ -x $(which kubectl) ]]; then alias k='kubectl';fi
if [[ -x $(which diff-so-fancy) ]]; then
  function difff (){
    diff -u $1 $2 | diff-so-fancy |less -R
  }
  function git-difff (){
    git diff --histogram $@ | diff-so-fancy | less -R
  }
fi

# for tmux
## when execute ssh, reflect tmux window_name in connection name
function ssh() {
  if [[ -n $(printenv TMUX) ]]
  then
    local window_name=$(tmux display -p '#{window_name}')
    tmux rename-window -- "$@[-1]" # zsh specified
    # tmux rename-window -- "${!#}" # for bash
    command ssh $@
    tmux rename-window $window_name
  else
    command ssh $@
  fi
}

# setting for asdf
. $HOME/.asdf/asdf.sh

# for each Shell
if [[ "${SHELL}" =~ "bash" ]]
then  # bash
  . ~/.shell/bash/setting
  . ~/.shell/bash/completion

elif [[ "${SHELL}" =~ "zsh" ]]
then  # zsh
  . ~/.shell/zsh/setting
  . ~/.shell/zsh/completion
  . ~/.shell/zsh/zplugin
fi

# for each OS
if [[ "$(uname)" = 'Darwin' ]]
then  # macOS
  export OS='Mac'
  . $HOME/.shell/mac

elif [[ "$(uname -r)" =~ ^.*-Microsoft$ ]]
then  # Windows Subsystem for Linux
  export OS='WSL'
  . $HOME/.shell/wsl

elif [[ "$(uname)" = 'Linux' ]]
then  # Linux
  export OS='Linux'
  . $HOME/.shell/linux

elif [[ "$(uname)" = 'FreeBSD' ]]
then  # FreeBSD
  export OS='FreeBSD'
  alias l='ls'
  alias ll='ls -lG'
  alias lll='ls -alG'
  alias updatedb='/usr/libexec/locate.updatedb'
fi

