#!/usr/bin/env zsh

###########################################################
# Completion

zstyle ':completion:*' list-colors "${LS_COLORS}"
# 単語の入力途中でもTab補完を有効化
setopt complete_in_word
# 補完候補をハイライト
zmodload -i zsh/complist
zstyle ':completion:*:default' menu select=1
# 補完をhjklで移動
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
# キャッシュの利用による補完の高速化
zstyle ':completion::complete:*' use-cache true
# 補完リストの表示間隔を狭くする
setopt list_packed
# コマンドの打ち間違いを指摘してくれる
setopt correct
SPROMPT="correct: $RED%R$DEFAULT -> $GREEN%r$DEFAULT ? [Yes/No/Abort/Edit] => "

rows=(
  #"COMMAND,OPTS"
  "kubectl,completion zsh"
  "pip,completion --zsh"
  "helm,completion zsh"
  "chezmoi,completion zsh"
  "gh,completion -s zsh"
  "mise,completion zsh"
  "fzf,--zsh"
)

for r in "${rows[@]}"; do
  IFS=',' read -r COMMAND OPTS <<< "$r"
  FILE=$HOME/.completions/_$COMMAND
  command -v $COMMAND >/dev/null && [[ ! -f $FILE || ! -s $FILE ]] && ( eval $COMMAND $OPTS > $FILE )
done

# load completion files by fpath
fpath=(
"$HOME/.completions"
"${fpath[@]}"
)
autoload -Uz compinit && compinit

# explicitly source key-bingings.zsh to call bindkey.
source $HOME/.completions/_fzf
