#!/usr/bin/env zsh

# variables
fzf_path=$(asdf where fzf)


# create completion files
if [ ! -f $HOME/.completions ]; then
  mkdir -p $HOME/.completions
fi
if [ -n "$(which kubectl)" ]; then
  if [ ! -f "$HOME/.completions/kubectl_completion_zsh" ]; then
    kubectl completion zsh > $HOME/.completions/kubectl_completion_zsh
  fi
fi
if [ -n "$(which pip)" ]; then
  if [ ! -f "$HOME/.completions/pip_completion_zsh" ]; then
    cat << '_EOF_' > $HOME/.completions/pip_completion_zsh
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
_EOF_
  fi
fi
if [ -n "$(which helm)" ]; then
  if [ ! -f "$HOME/.completions/helm_completion_zsh" ]; then
    helm completion zsh > $HOME/.completions/helm_completion_zsh
  fi
fi
if [ -n "$(which chezmoi)" ]; then
  if [ ! -f "$HOME/.completions/chezmoi_completion_zsh" ]; then
    chezmoi completion zsh > $HOME/.completions/chezmoi_completion_zsh
  fi
fi


# load completion files
completions=(
"$HOME/.asdf/completions/asdf.zsh"
"${fzf_path}/shell/completion.zsh"
"${fzf_path}/shell/key-bindings.zsh"
"/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
"$HOME/.completions/kubectl_completion_zsh"
"$HOME/.completions/pip_completion_zsh"
"$HOME/.completions/helm_completion_zsh"
"$HOME/.completions/chezmoi_completion_zsh"
)
for _file in ${completions[@]}; do
  if [ -e $_file ]; then
    . $_file
  fi
done
