#!/usr/bin/env zsh

###########################################################
# fzf setup
export FZF_DEFAULT_OPTS="--height 30% --reverse --border --ansi"
# fbr - checkout git branch
fbr() {
  local branches branch
    branches=$(git branch -vv) &&
    branch=$(echo "$branches" | fzf +m) &&
  git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
}
# fbrm - checkout git branch (including remote branches)
fbrm() {
  local branches branch
  branches=$(git branch --all | grep -v HEAD) &&
  branch=$(echo "$branches" |
  fzf -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}
# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}
# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
      -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

###########################################################
# ghq + fzf on tmux (https://www.matsub.net/posts/2017/12/01/ghq-fzf-on-tmux)
function dev() {
  ghq_dir=$(ghq list | fzf)
  if [ $? -eq 0 ]; then
    moveto=$(ghq root)/$ghq_dir
    cd $moveto

    # rename window if in tmux, pane if in herdr
    repo_name=${moveto##*/}
    if [[ ! -z ${TMUX} ]]
    then
      tmux rename-window ${repo_name//./-}
    elif [[ ${HERDR_ENV} == 1 && -n ${HERDR_PANE_ID} ]]
    then
      herdr pane rename "${HERDR_PANE_ID}" "${repo_name//./-}" >/dev/null 2>&1
    fi
  fi
  unset ghq_dir
}
zle -N dev
bindkey '^G' dev
