#!/usr/bin/env zsh

###########################################################
# starship
[ -x $(which starship) ] && eval "$(starship init zsh)"

###########################################################
# mise
[ -f $HOME/.local/bin/mise ] && eval "$($HOME/.local/bin/mise activate zsh)"
