#!/usr/bin/env zsh

###########################################################
# Common setting

bindkey -e
bindkey "\C-f" forward-word
bindkey "\C-b" backward-word
setopt auto_cd
autoload -U colors
colors
#WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
WORDCHARS='_-|'
