#!/usr/bin/env zsh
###########################################################
# Pre configuration
#
ZINIT_VERSION=v3.7
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [[ ! -d $ZINIT_HOME ]];then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git -b ${ZINIT_VERSION} "${ZINIT_HOME}"
fi
source "$ZINIT_HOME/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

###########################################################
# Packages

zinit load "zsh-users/zsh-syntax-highlighting"
zinit load "zsh-users/zsh-history-substring-search"
zinit load "zsh-users/zsh-autosuggestions"
zinit load "zsh-users/zsh-completions"
#zinit "chrissicool/zsh-256color"
#zinit "mafredri/zsh-async"

