#!/usr/bin/env sh

# .inputrc (Mac)
if [ "$(uname)" == 'Darwin' ]; then
if [ -L ~/.inputrc ]; then
	unlink ~/.inputrc
elif [ -f ~/.inputrc ]; then
	rm ~/.inputrc
fi
	ln -s ~/dotfiles/.inputrc ~/
	source ~/.inputrc
	echo ".inputrc is deploy to ~/"
fi

# .bashrc_self
if [ -L ~/.bashrc_self ]; then
	unlink ~/.bashrc_self
elif [ -f ~/.bashrc_self ]; then
	rm ~/.bashrc_self
else
	echo "if [ -f ~/.bashrc_self ]; then source ~/.bashrc_self; fi" >> ~/.bashrc
fi
ln -s ~/dotfiles/.bashrc_self ~/
source ~/.bashrc
echo ".bashrc_self is deploy to ~/"

# vim plugin
if [ ! -d ~/.vim ];then
	mkdir ~/.vim
	for i in $(ls ~/dotfiles/.vim/ | grep -v bundle)
	do
		ln -s ~/dotfiles/.vim/$i ~/.vim/
	done
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > ~/.vim/install.sh
	sh ~/.vim/install.sh
	rm -rf ~/.vim/install.sh
	echo "Complete vim plugins Setup."
fi

# vim-undofile folder
if [ ! -d ~/vimundo ]; then
	mkdir ~/vimundo
	echo "mkdir ~/vimundo"
fi

