#!/usr/bin/env zsh

# source some files
completions=(
"$HOME/.asdf/completions/asdf.bash"
"$HOME/.fzf/shell/completion.zsh"
"$HOME/.fzf/shell/key-bindings.zsh"
"/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" # for macOS
"/Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion"           # for macOS
"/Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion"   # for macOS
)
for _file in ${completions[@]}; do
  if [ -e $_file ]; then
    . $_file
  fi
done

# pip
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip

# kubectl completion
if kubectl help &> /dev/null; then
  alias k=kubectl
  if [[ ! -e $HOME/.kubectl_completion_zsh ]]; then
    kubectl completion zsh > $HOME/.kubectl_completion_zsh
  fi
  . $HOME/.kubectl_completion_zsh
fi
