#!/usr/bin/env zsh

# source some files
completions=(
"$HOME/.asdf/completions/asdf.bash"
"/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
"/usr/local/opt/fzf/shell/completion.zsh"
"/usr/local/opt/fzf/shell/key-bindings.zsh"
)
for _file in ${completions[@]}; do
  if [ -e $_file ]; then
    . $_file
  fi
done

# pip
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] ) )
}
compctl -K _pip_completion pip
