#!/usr/bin/env zsh
###########################################################
# Common setting

bindkey -e
bindkey "\C-f" forward-word
bindkey "\C-b" backward-word
setopt auto_cd
autoload -U colors
colors
#WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
WORDCHARS='_-|'

###########################################################
# Prompt

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
#zstyle ':vcs_info:*' formats '<%{'${fg[red]}'%}%b%{'$reset_color'%}>'
zstyle ':vcs_info:*' formats '%F{green}<%F{red}%b%F{green}>'

setopt prompt_subst
precmd () {
  LANG=en_US.UTF-8 vcs_info
  if [ $UID -eq 0 ]; then
    PROMPT="${vcs_info_msg_0_}%F{green}[%F{red}%n%F{green}@%m: %c]%%%{$reset_color%} "
  else
    PROMPT="${vcs_info_msg_0_}%F{green}[%n@%m: %c]%{$reset_color%}%% "
  fi
}

###########################################################
# Completion

## 補完機能有効にする
autoload -U compinit
compinit -u
zstyle ':completion:*' list-colors "${LS_COLORS}"
# 単語の入力途中でもTab補完を有効化
setopt complete_in_word
# 補完候補をハイライト
zmodload -i zsh/complist
zstyle ':completion:*:default' menu select=1
# 補完をhjklで移動
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
# キャッシュの利用による補完の高速化
zstyle ':completion::complete:*' use-cache true
# 補完リストの表示間隔を狭くする
setopt list_packed
# コマンドの打ち間違いを指摘してくれる
setopt correct
SPROMPT="correct: $RED%R$DEFAULT -> $GREEN%r$DEFAULT ? [Yes/No/Abort/Edit] => "

###########################################################
# History

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt hist_ignore_dups     # 前と重複する行は記録しない
setopt share_history        # 同時に起動したzshの間でヒストリを共有する
setopt hist_reduce_blanks   # 余分なスペースを削除してヒストリに保存する
setopt HIST_IGNORE_SPACE    # 行頭がスペースのコマンドは記録しない
setopt HIST_IGNORE_ALL_DUPS # 履歴中の重複行をファイル記録前に無くす
setopt HIST_FIND_NO_DUPS    # 履歴検索中、(連続してなくとも)重複を飛ばす
setopt HIST_NO_STORE        # histroyコマンドは記録しない
# http://mollifier.hatenablog.com/entry/20090728/p1
#zshaddhistory() {
#    local line=${1%%$'\n'} #コマンドライン全体から改行を除去したもの
#    local cmd=${line%% *}  # １つ目のコマンド
#    # 以下の条件をすべて満たすものだけをヒストリに追加する
#    [[ ${#line} -ge 5
#        && ${cmd} != (l|l[sal])
#        && ${cmd} != (cd)
#        && ${cmd} != (m|man)
#        && ${cmd} != (r[mr])
#    ]]
#}
