mac:
  brew:
    - "ansible"
    - "autoconf"
    - "automake"
    - "bash-completion"
    - "cask"
    - "clang-format"
    - "coreutils"
    - "ctags"
    - "fzf"
    - "git"
    - "gpg"
    - "htop"
    - "hub"
    - "iproute2mac"
    - "jq"
    - "jsonnet"
    - "kubectx"
    - "kubernetes-cli"
    - "libtool"
    - "libxslt"
    - "libyaml"
    - "macvim"
    - "mas"
    - "mysql-client"
    - "neovim"
    - "nkf"
    - "openssl"
    - "pv"
    - "readline"
    - "rename"
    - "telnet"
    - "terraform"
    - "the_silver_searcher"
    - "tig"
    - "tmux"
    - "tree"
    - "unixodbc"
    - "watch"
    - "wget"
    - "zsh"
  cask:

    - "alfred"
    - "bettertouchtool"
    - "coccinellida"
    - "discord"
    - "disk-inventory-x"
    - "firefox"
    - "google-backup-and-sync"
    - "google-chrome"
    - "google-cloud-sdk"
    - "google-japanese-ime"
    - "homebrew/cask-drivers/fitbit-connect"
    - "homebrew/cask-versions/microsoft-remote-desktop-beta"
    - "iterm2-beta"
    - "karabiner-elements"
    - "kindle"
    - "nextcloud"
    - "osxfuse"
    - "skim"
    - "skitch"
    - "slack"
    - "the-unarchiver"
    - "thunderbird"
    - "visual-studio-code"
    - "vlc"
    - "vnc-viewer"
    - "wireshark"
  mas:
    # Line
    - 539883307
    # BetterSnapTool
    - 417375580
    # Helium
    - 1018899653
redhat:
  yum:
    - "@base"
    - "epel-release"
    - "git"
  yum-epel:
    - "neovim"
    - "colordiff"
