mac:
  - command: "brew install"
    precommand: "brew update"
    list:
      - "ansible"
      - "autoconf"
      - "automake"
      - "bash-completion"
      - "bats"
      - "cask"
      - "clang-format"
      - "coreutils"
      - "ctags"
      - "dive"
      - "gh"
      - "git"
      - "gmailctl"
      - "goreleaser"
      - "gpg"
      - "grpcurl"
      - "htop"
      - "hub"
      - "iproute2mac"
      - "jq"
      - "jsonnet"
      - "libtool"
      - "libxslt"
      - "libyaml"
      - "macvim"
      - "mas"
      - "mysql-client"
      - "neovim"
      - "nkf"
      - "octant"
      - "openssl"
      - "pv"
      - "readline"
      - "rename"
      - "telnet"
      - "terraform"
      - "the_silver_searcher"
      - "tig"
      - "tmux"
      - "tree"
      - "unixodbc"
      - "watch"
      - "wget"
      - "zsh"
  - command: "brew cask install"
    list:
      - "alfred"
      - "altair-graphql-client"
      - "bettertouchtool"
      - "coccinellida"
      - "discord"
      - "disk-inventory-x"
      - "firefox"
      - "google-backup-and-sync"
      - "google-chrome"
      - "google-cloud-sdk"
      - "google-japanese-ime"
      - "homebrew/cask-drivers/fitbit-connect"
      - "homebrew/cask-versions/microsoft-remote-desktop-beta"
      - "iterm2-beta"
      - "karabiner-elements"
      - "kindle"
      - "nextcloud"
      - "osxfuse"
      - "postman"
      - "skim"
      - "skitch"
      - "slack"
      - "sourcetrail"
      - "the-unarchiver"
      - "thunderbird"
      - "toggl-track"
      - "visual-studio-code"
      - "vlc"
      - "vnc-viewer"
      - "wireshark"
      - "zoomus"
  - command: "mas install"
    list:
      # Line
      - 539883307
      # BetterSnapTool
      - 417375580
      # Helium
      - 1018899653
      # MeetingBar (macOS 1.15)
      #- 1532419400
redhat:
  - command: "yum install -y"
    precommand: "yum update -y"
    list:
      - "@base"
      - "@development"
      - "epel-release"
      - "git"
      - "libffi-devel"
      - "bzip2-devel"
      - "readline-devel"
      - "sqlite-devel"
      - "openssl-devel"
      - "zlib-devel"
  - command: "yum --enablerepo=epel install -y"
    list:
      - "neovim"
      - "colordiff"
