#!/bin/sh
# Author: Kitazawa
# On the premise that  Xcode Homebrew is already installed.

sudo echo ""
if [ $? != 0 ]
then
	exit 1
fi

mkdir ~/.vim
if [ $? != 0 ]; then exit 1; fi
for i in $(ls ~/dotfiles/.vim/ | grep -v bundle)
do
	ln -s ~/dotfiles/.vim/$i ~/.vim/
done
brew install lua -y
brew reinstall vim --with-lua -y
brew install clang-format
curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > ~/.vim/install.sh
sh ~/.vim/install.sh
rm -rf ~/.vim/install.sh

brew install pyenv
echo '' >> ~/.bashrc
echo '# pyenv' >> ~/.bashrc
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc
tmp=`pyenv install --list | grep -G "^  [0-9][0-9|\.]*[0-9]$" |sort |tail -1`
pyenv install $tmp
pyenv global $tmp
pyenv rehash
sudo easy_install pip
sudo pip install pep8 pyflakes
sudo pip install pep8 pytest pytest-pep8

exit 0
