#!/usr/bin/env bash

completions=(
"$HOME/.asdf/completions/asdf.bash"
"/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
"/usr/local/opt/fzf/shell/completion.bash"
"/usr/local/opt/fzf/shell/key-bindings.bash"
)
for _file in ${completions[@]}; do
  if [ -e $_file ]; then
    . $_file
  fi
done

# pip
if pip --version >/dev/null 2>&1; then
  _pip_completion()
  {
      COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
                     COMP_CWORD=$COMP_CWORD \
                     PIP_AUTO_COMPLETE=1 $1 ) )
  }
  complete -o default -F _pip_completion pip
fi

# kubectl
if kubectl help > /dev/null 2>&1; then
  . <(kubectl completion bash)
  alias k=kubectl
  complete -o default -F __start_kubectl k
fi

